//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuluseuranta.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kuluseuranta.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisää kategoria.
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uuden kategorian lisäys.
        /// </summary>
        public static string AddNewCategoryMessage {
            get {
                return ResourceManager.GetString("AddNewCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uuden maksun lisäys.
        /// </summary>
        public static string AddNewPaymentMessage {
            get {
                return ResourceManager.GetString("AddNewPaymentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uuden alakategorian lisäys.
        /// </summary>
        public static string AddNewSubCategoryMessage {
            get {
                return ResourceManager.GetString("AddNewSubCategoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uuden käyttäjän lisäys.
        /// </summary>
        public static string AddNewUserMessage {
            get {
                return ResourceManager.GetString("AddNewUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisää maksu.
        /// </summary>
        public static string AddPayment {
            get {
                return ResourceManager.GetString("AddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisää alakategoria.
        /// </summary>
        public static string AddSubCategory {
            get {
                return ResourceManager.GetString("AddSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisää käyttäjä.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pääkäyttäjä.
        /// </summary>
        public static string AdminUser {
            get {
                return ResourceManager.GetString("AdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaikki kategoriat.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaikki alakategoriat.
        /// </summary>
        public static string AllSubCategories {
            get {
                return ResourceManager.GetString("AllSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksun määrä.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takaisin.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salasanan vaihtoa ei voi suorittaa.
        /// </summary>
        public static string CannotChangePassword {
            get {
                return ResourceManager.GetString("CannotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei voi tallentaa: {0}.
        /// </summary>
        public static string CannotSaveBecauseX {
            get {
                return ResourceManager.GetString("CannotSaveBecauseX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallennusta ei voi suorittaa koska kategoriaa ei ole valittu listalta.
        /// </summary>
        public static string CannotSaveCategoryNotSelectedMessage {
            get {
                return ResourceManager.GetString("CannotSaveCategoryNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallennusta ei voi suorittaa koska maksua ei ole valittu listalta.
        /// </summary>
        public static string CannotSavePaymentNotSelectedMessage {
            get {
                return ResourceManager.GetString("CannotSavePaymentNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallennusta ei voi suorittaa koska alakategoriaa ei ole valittu listalta.
        /// </summary>
        public static string CannotSaveSubCategoryNotSelectedMessage {
            get {
                return ResourceManager.GetString("CannotSaveSubCategoryNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallennusta ei voi suorittaa koska käyttäjää ei ole valittu listalta.
        /// </summary>
        public static string CannotSaveUserNotSelectedMessage {
            get {
                return ResourceManager.GetString("CannotSaveUserNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriat.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kategoria puuttuu.
        /// </summary>
        public static string CategoryIsMissing {
            get {
                return ResourceManager.GetString("CategoryIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriat on haettu {0}.
        /// </summary>
        public static string CategoryListUpdatedAtX {
            get {
                return ResourceManager.GetString("CategoryListUpdatedAtX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorioiden ylläpito.
        /// </summary>
        public static string CategoryMaintenance {
            get {
                return ResourceManager.GetString("CategoryMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorian valinta.
        /// </summary>
        public static string CategorySelection {
            get {
                return ResourceManager.GetString("CategorySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorian {0} tiedot on päivitetty.
        /// </summary>
        public static string CategorysXDetailsAreUpdated {
            get {
                return ResourceManager.GetString("CategorysXDetailsAreUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoria {0} on poistettu.
        /// </summary>
        public static string CategoryXIsDeleted {
            get {
                return ResourceManager.GetString("CategoryXIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaihda salasana.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muutoksia ei ole vielä tallennettu. Tallennetaanko nyt?.
        /// </summary>
        public static string ChangesAreNotSavedYetSaveNowMessage {
            get {
                return ResourceManager.GetString("ChangesAreNotSavedYetSaveNowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muuttuneet tiedot on tallennettu.
        /// </summary>
        public static string ChangesAreSaved {
            get {
                return ResourceManager.GetString("ChangesAreSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikkaa &quot;Hae kategoriat&quot; hakeaksesi kategorioiden tiedot.
        /// </summary>
        public static string ClickGetCategoriesMessage {
            get {
                return ResourceManager.GetString("ClickGetCategoriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikkaa &quot;Hae maksut&quot; hakeaksesi maksujen tiedot.
        /// </summary>
        public static string ClickGetPaymentsMessage {
            get {
                return ResourceManager.GetString("ClickGetPaymentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse aikaväli sekä haluttu kategoria mahdollisen alakategorian kanssa ja klikkaa &quot;Hae&quot; hakeaksesi raportin tiedot.
        /// </summary>
        public static string ClickGetReportsMessage {
            get {
                return ResourceManager.GetString("ClickGetReportsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikkaa &quot;Hae alakategoriat&quot; hakeaksesi alakategorioiden tiedot.
        /// </summary>
        public static string ClickGetSubCategoriesMessage {
            get {
                return ResourceManager.GetString("ClickGetSubCategoriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klikkaa &quot;Hae käyttäjät&quot; hakeaksesi käyttäjien tiedot.
        /// </summary>
        public static string ClickGetUsersMessage {
            get {
                return ResourceManager.GetString("ClickGetUsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sulje.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaikille yleinen.
        /// </summary>
        public static string CommonForAll {
            get {
                return ResourceManager.GetString("CommonForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poiston vahvistaminen.
        /// </summary>
        public static string ConfirmDeleteting {
            get {
                return ResourceManager.GetString("ConfirmDeleteting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haluatko varmasti poistaa kategorian {0} alakategorioineen?.
        /// </summary>
        public static string ConfirmDeletetingCategoryX {
            get {
                return ResourceManager.GetString("ConfirmDeletetingCategoryX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haluatko varmasti poistaa maksun {0}?.
        /// </summary>
        public static string ConfirmDeletetingPaymentX {
            get {
                return ResourceManager.GetString("ConfirmDeletetingPaymentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haluatko varmasti poistaa alakategorian {0}?.
        /// </summary>
        public static string ConfirmDeletetingSubCategoryX {
            get {
                return ResourceManager.GetString("ConfirmDeletetingSubCategoryX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haluatko varmasti poistaa käyttäjän {0}?.
        /// </summary>
        public static string ConfirmDeletetingUserX {
            get {
                return ResourceManager.GetString("ConfirmDeletetingUserX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopioi uutena.
        /// </summary>
        public static string CopyAsNew {
            get {
                return ResourceManager.GetString("CopyAsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallennettu.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valuutta.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiedot haettu aikaväliltä: {0}-{1}. Kategorian valinnat: {2}/{3}.
        /// </summary>
        public static string DataRetrievedDetailsMessage {
            get {
                return ResourceManager.GetString("DataRetrievedDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poista kategoria.
        /// </summary>
        public static string DeleteCategory {
            get {
                return ResourceManager.GetString("DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poista maksu.
        /// </summary>
        public static string DeletePayment {
            get {
                return ResourceManager.GetString("DeletePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poista alakategoria.
        /// </summary>
        public static string DeleteSubCategory {
            get {
                return ResourceManager.GetString("DeleteSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poista käyttäjä.
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuvaus.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eräpäivä.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sähköposti.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sähköposti on virheellinen.
        /// </summary>
        public static string EmailIsIncorrect {
            get {
                return ResourceManager.GetString("EmailIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etunimi.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etunimi puuttuu.
        /// </summary>
        public static string FirstNameIsMissing {
            get {
                return ResourceManager.GetString("FirstNameIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kokonimi.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hae.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hae kategoriat.
        /// </summary>
        public static string GetCategories {
            get {
                return ResourceManager.GetString("GetCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hae maksut.
        /// </summary>
        public static string GetPayments {
            get {
                return ResourceManager.GetString("GetPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hae alakategoriat.
        /// </summary>
        public static string GetSubCategories {
            get {
                return ResourceManager.GetString("GetSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hae käyttäjät.
        /// </summary>
        public static string GetUsers {
            get {
                return ResourceManager.GetString("GetUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukunimi.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sukunimi puuttuu.
        /// </summary>
        public static string LastNameIsMissing {
            get {
                return ResourceManager.GetString("LastNameIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viimeisimmät.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjautuneena: {0}.
        /// </summary>
        public static string LoggedUserX {
            get {
                return ResourceManager.GetString("LoggedUserX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjautuminen.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjaudu.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjautuminen epäonnistui.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirjautuminen epäonnistui! Tarkista käyttäjätunnus ja salasana..
        /// </summary>
        public static string LoginFailedCheckUsernameAndPassword {
            get {
                return ResourceManager.GetString("LoginFailedCheckUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muokattu.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uusi kategoria {0} on tallennettu.
        /// </summary>
        public static string NewCategoryXIsSaved {
            get {
                return ResourceManager.GetString("NewCategoryXIsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uusi salasana pitää olla eri kuin vaihdettava salasana!.
        /// </summary>
        public static string NewPasswordCannotBeOldPassword {
            get {
                return ResourceManager.GetString("NewPasswordCannotBeOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uusi maksu {0} on tallennettu.
        /// </summary>
        public static string NewPaymentXIsSaved {
            get {
                return ResourceManager.GetString("NewPaymentXIsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uusi alakategoria {0} on tallennettu.
        /// </summary>
        public static string NewSubCategoryXIsSaved {
            get {
                return ResourceManager.GetString("NewSubCategoryXIsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uusi käyttäjä {0} on tallennettu.
        /// </summary>
        public static string NewUserXIsSaved {
            get {
                return ResourceManager.GetString("NewUserXIsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavallinen käyttäjä.
        /// </summary>
        public static string NormalUser {
            get {
                return ResourceManager.GetString("NormalUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muistiinpanot.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanha salasana.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksettu.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maksupäivä puuttuu.
        /// </summary>
        public static string PaidDateIsMissing {
            get {
                return ResourceManager.GetString("PaidDateIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salasana.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salasana on vaihdettu.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salasanan vaihto.
        /// </summary>
        public static string PasswordChanging {
            get {
                return ResourceManager.GetString("PasswordChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salasanan vaihto ei onnistunut!.
        /// </summary>
        public static string PasswordChangingFailed {
            get {
                return ResourceManager.GetString("PasswordChangingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salasanan vahvistus.
        /// </summary>
        public static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salasanan pituuden on oltava vähintään {0} merkkiä..
        /// </summary>
        public static string PasswordLengthMustBeAtLeastXMarks {
            get {
                return ResourceManager.GetString("PasswordLengthMustBeAtLeastXMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salasana ja sen vahvistus ei täsmää!.
        /// </summary>
        public static string PasswordsDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaihdettava salasana.
        /// </summary>
        public static string PasswordToChange {
            get {
                return ResourceManager.GetString("PasswordToChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksajan tilinumero.
        /// </summary>
        public static string PayersAccount {
            get {
                return ResourceManager.GetString("PayersAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksajan nimi.
        /// </summary>
        public static string PayersName {
            get {
                return ResourceManager.GetString("PayersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksu on poistettu.
        /// </summary>
        public static string PaymentIsDeleted {
            get {
                return ResourceManager.GetString("PaymentIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksut on haettu {0}.
        /// </summary>
        public static string PaymentListUpdatedAtX {
            get {
                return ResourceManager.GetString("PaymentListUpdatedAtX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksujen tarkastelu.
        /// </summary>
        public static string PaymentReports {
            get {
                return ResourceManager.GetString("PaymentReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksujen syöttö.
        /// </summary>
        public static string PaymentsEntering {
            get {
                return ResourceManager.GetString("PaymentsEntering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksun {0} tiedot on päivitetty.
        /// </summary>
        public static string PaymentsXDetailsAreUpdated {
            get {
                return ResourceManager.GetString("PaymentsXDetailsAreUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to laskuttaja puuttuu.
        /// </summary>
        public static string PayorIsMissing {
            get {
                return ResourceManager.GetString("PayorIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saajan tilinumero.
        /// </summary>
        public static string PayorsAccount {
            get {
                return ResourceManager.GetString("PayorsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saajan nimi.
        /// </summary>
        public static string PayorsName {
            get {
                return ResourceManager.GetString("PayorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aikaväli.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Henkilökohtainen.
        /// </summary>
        public static string PersonalOnly {
            get {
                return ResourceManager.GetString("PersonalOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viitenumero.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekisteröidy.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pääkategoriaa ei voi poistaa.
        /// </summary>
        public static string RootCategoryCannotBeDeleted {
            get {
                return ResourceManager.GetString("RootCategoryCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valittu pääkategoria.
        /// </summary>
        public static string RootCategorySelected {
            get {
                return ResourceManager.GetString("RootCategorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivejä: {0} kpl.
        /// </summary>
        public static string RowsCountX {
            get {
                return ResourceManager.GetString("RowsCountX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summa: {0}.
        /// </summary>
        public static string RowsSumX {
            get {
                return ResourceManager.GetString("RowsSumX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saman niminen kategoria on jo listalla!.
        /// </summary>
        public static string SameNameCategoryListedAlready {
            get {
                return ResourceManager.GetString("SameNameCategoryListedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saman laskuttajan maksu on jo listalla!.
        /// </summary>
        public static string SameNamePaymentListedAlready {
            get {
                return ResourceManager.GetString("SameNamePaymentListedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saman niminen alakategoria on jo listalla!.
        /// </summary>
        public static string SameNameSubCategoryListedAlready {
            get {
                return ResourceManager.GetString("SameNameSubCategoryListedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saman niminen käyttäjä on jo listalla!.
        /// </summary>
        public static string SameNameUserListedAlready {
            get {
                return ResourceManager.GetString("SameNameUserListedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallenna.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse ensin kategoria.
        /// </summary>
        public static string SelectCategoryFirstMessage {
            get {
                return ResourceManager.GetString("SelectCategoryFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitulla kategorialla ei ole alakategorioita.
        /// </summary>
        public static string SelectedCategoryHasNoSubCategories {
            get {
                return ResourceManager.GetString("SelectedCategoryHasNoSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valittu kategoria: {0}.
        /// </summary>
        public static string SelectedCategoryX {
            get {
                return ResourceManager.GetString("SelectedCategoryX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valittu maksu: {0}.
        /// </summary>
        public static string SelectedPaymentX {
            get {
                return ResourceManager.GetString("SelectedPaymentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valittu alakategoria: {0}.
        /// </summary>
        public static string SelectedSubCategoryX {
            get {
                return ResourceManager.GetString("SelectedSubCategoryX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valittu käyttäjä: {0}.
        /// </summary>
        public static string SelectedUserX {
            get {
                return ResourceManager.GetString("SelectedUserX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjätunnuksen asettaminen.
        /// </summary>
        public static string SettingUserName {
            get {
                return ResourceManager.GetString("SettingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjätunnuksen asettaminen epäonnistui: {0}.
        /// </summary>
        public static string SettingUserNameFailedBecauseOfX {
            get {
                return ResourceManager.GetString("SettingUserNameFailedBecauseOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aseta käyttäjätunnus.
        /// </summary>
        public static string SetUserName {
            get {
                return ResourceManager.GetString("SetUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alakategoriat.
        /// </summary>
        public static string SubCategories {
            get {
                return ResourceManager.GetString("SubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alakategoria.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alakategoria puuttuu.
        /// </summary>
        public static string SubCategoryIsMissing {
            get {
                return ResourceManager.GetString("SubCategoryIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alakategoriat on haettu {0}.
        /// </summary>
        public static string SubCategoryListUpdatedAtX {
            get {
                return ResourceManager.GetString("SubCategoryListUpdatedAtX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alakategorioiden ylläpito.
        /// </summary>
        public static string SubCategoryMaintenance {
            get {
                return ResourceManager.GetString("SubCategoryMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alakategorian {0} tiedot on päivitetty.
        /// </summary>
        public static string SubCategorysXDetailsAreUpdated {
            get {
                return ResourceManager.GetString("SubCategorysXDetailsAreUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alakategoria {0} on poistettu.
        /// </summary>
        public static string SubCategoryXIsDeleted {
            get {
                return ResourceManager.GetString("SubCategoryXIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyyppi.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallennuksessa tapahtui odottamaton virhe!.
        /// </summary>
        public static string UnexpectedErrorOccurredWhileSaving {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurredWhileSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallentamattomia muutoksia.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjätunnus.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjät on haettu {0}.
        /// </summary>
        public static string UserListUpdatedAtX {
            get {
                return ResourceManager.GetString("UserListUpdatedAtX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjien hallinta.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjätunnusta ei voi asettaa koska se on jo käytössä. Valitse toinen käyttäjätunnus..
        /// </summary>
        public static string UserNameAlreadyInUseMessage {
            get {
                return ResourceManager.GetString("UserNameAlreadyInUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjärooli.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjät.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjän {0} tiedot on päivitetty.
        /// </summary>
        public static string UsersXDetailsAreUpdated {
            get {
                return ResourceManager.GetString("UsersXDetailsAreUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käyttäjä {0} on poistettu.
        /// </summary>
        public static string UserXIsDeleted {
            get {
                return ResourceManager.GetString("UserXIsDeleted", resourceCulture);
            }
        }
    }
}
